"""Authoritative public result-fact field names (F07).

The catalog projection in ``contracts`` and the executor in ``tools`` must agree
on which result fields are publicly visible.  That allowlist used to live in the
execution center, so the read-only catalog had to import the executor to read
it.  It now lives here: a small, low-dependency module that both sides import,
with no reverse edge into the execution layer.

The names are a review boundary, not a schema owner: metric/dimension contracts
still decide which of them a given metric may return.
"""

from . import analytical_handlers
from .fabric_source_queries import FACT_FIELDS as _FABRIC_FACT_FIELDS

PUBLIC_FACT_FIELDS = {
    "query_rank", "rank_tie_count", "rank_population_count", "rank_unknown_value_count",
    "task_status_unfilled_rows",
    "execute_status_unfilled_rows",
    "verified_linked_bill_count",
    "requirement_currency_missing_rows",
    "requirement_currency_conflict_details",
    "rows_without_execution_id",
    "pattern_read_at",
    "pattern_read_utc_at",
    "pattern_task_modified_max",
    "pattern_execute_modified_max",
    "pattern_scope_rows",
    "pattern_scope_unknown_rows",
    "pattern_display_groups",
    "known_task_count",
    "known_execution_count",
    "known_executor_count",
    "known_candidate_product_count",
    "recorded_linked_detail_count",
    "verified_linked_detail_count",
    "recorded_linked_bill_count",
    "tasks_with_recorded_link",
    "tasks_with_verified_link",
    "tasks_with_found_record",
    "tasks_with_not_found_record",
    "tasks_with_suitable_record",
    "tasks_with_unsuitable_record",
    "tasks_with_received_record",
    "tasks_with_not_received_record",
    "tasks_with_unfilled_found",
    "tasks_with_unfilled_feedback",
    "tasks_with_unfilled_receive",
    "tasks_with_completed_status_record",
    "task_status_conflict_count",
    "execute_status_conflict_count",
    "task_status_unknown_rows",
    "execute_status_unknown_rows",
    "unrecognized_flag_rows",
    "task_identity_unknown_rows",
    "execution_identity_unknown_rows",
    "executor_identity_unknown_rows",
    "candidate_product_unfilled_rows",
    "candidate_product_nonatomic_rows",
    "recorded_unverified_link_rows",
    "result_source_rows",
    "amount_key_count",
    "known_amount",
    "known_amount_keys",
    "unresolved_amount_rows",
    "currency_known_amount",
    "currency_amount_keys",
    "currency_unresolved_rows",
    "currency_missing_rows",
    "unclassified_source_amount",
    "unclassified_source_amount_min",
    "unclassified_source_amount_max",
    "unclassified_source_row_count",
    "pattern_task_ref",
    "pattern_customer_ref",
    "pattern_salesperson_ref",
    "pattern_executor_ref",

    "sales_identity_ref",
    "known_net_rolls",
    "grouped_key_count",
    "matched_product_groups",
    "population_display_groups",
    "unit_baseline_scope_groups",
    "unit_display_groups",
    "unit_net_quantity",
    "unit_known_net_quantity",
    "sales_name_variant_count",
    "sales_missing_name_rows",
    "outbound_unattributed_sales_rows",
    "returns_unattributed_sales_rows",
    "unit_gross_flow_rows",
    "unit_return_flow_rows",
    "unit_gross_known_quantity",
    "unit_return_known_quantity",
    "unit_gross_known_rolls",
    "unit_return_known_rolls",
    "unit_gross_missing_quantity_rows",
    "unit_return_missing_quantity_rows",
    "unit_gross_missing_roll_rows",
    "unit_return_missing_roll_rows",

    "net_rolls",
    "baseline_scope_groups",
    "gross_flow_rows",
    "return_flow_rows",
    "gross_known_quantity",
    "return_known_quantity",
    "gross_known_rolls",
    "return_known_rolls",
    "gross_missing_quantity_rows",
    "return_missing_quantity_rows",
    "gross_missing_roll_rows",
    "return_missing_roll_rows",
    "gross_quantity",
    "return_quantity",
    "gross_rolls",
    "return_rolls",
    "outbound_candidate_rows",
    "outbound_matched_rows",
    "outbound_unmatched_rows",
    "outbound_excluded_rows",
    "outbound_unknown_rows",
    "outbound_unknown_document_rows",
    "outbound_missing_time_rows",
    "returns_candidate_rows",
    "returns_matched_rows",
    "returns_unmatched_rows",
    "returns_excluded_rows",
    "returns_unknown_rows",
    "returns_unknown_document_rows",
    "returns_missing_time_rows",

    "opening_unknown_key_rows",
    "closing_unknown_key_rows",
    "opening_unknown_unit_rows",
    "closing_unknown_unit_rows",
    "closing_unknown_whitelist_rows",

    "baseline_week",
    "baseline_frozen_at",
    "closing_read_at",
    "closing_utc_at",
    "observed_clock_offset_seconds",
    "opening_source_rows",
    "closing_source_rows",
    "opening_quantity",
    "closing_quantity",
    "opening_known_quantity",
    "closing_known_quantity",
    "opening_known_rolls",
    "closing_known_rolls",
    "opening_rolls",
    "closing_rolls",
    "comparable_quantity_delta",
    "opening_missing_quantity_rows",
    "closing_missing_quantity_rows",
    "opening_missing_roll_rows",
    "closing_missing_roll_rows",
    "opening_unknown_class_rows",
    "closing_unknown_class_rows",
    "closing_uncertain_membership_rows",
    "identity_uncertain",
    "opening_product_id_count",
    "closing_product_id_count",
    "opening_sku_id_count",
    "closing_sku_id_count",
    "population_union_groups",
    "new_group_count",
    "exited_group_count",
    "reduced_group_count",
    "unchanged_group_count",
    "increased_group_count",
    "unassessable_group_count",
    "population_new_group_count",
    "population_exited_group_count",
    "population_reduced_group_count",
    "population_unchanged_group_count",
    "population_increased_group_count",
    "population_unassessable_group_count",

    "pool_discountable_rolls",
    "pool_priced_rolls",
    "pool_overlap_rolls",
    "pool_unknown_label_rolls",
    "pool_unpriced_rolls",
    "pool_known_discountable_rolls",
    "pool_known_overlap_rolls",
    "numerator_value",
    "denominator_value",
    "known_subset_value",
    "scope_row_count",
    "assessed_row_count",
    "unassessable_row_count",
    "eligible_row_count",
    "missing_credit_days_count",
    "missing_bill_time_count",
    "eligibility_coverage_rate",
    "metric_value",
    "comparison_value",
    "delta_value",
    "change_rate",
    "target_amount_rmb",
    "actual_amount_rmb",
    "gap_amount_rmb",
    "target_amount_original",
    "actual_amount_original",
    "gap_amount_original",
    "source_scope_base_row_count",
    "source_scope_internal_row_count",
    "source_scope_unrepresented_internal_count",
    "source_scope_unknown_internal_count",
    "completion_rate",
    "known_value_count",
    "missing_value_count",
    "value_coverage_rate",
    "current_known_value_count",
    "current_missing_value_count",
    "comparison_known_value_count",
    "comparison_missing_value_count",
    "cost_turnover_days",
    "effective_operating_months",
    "expected_snapshot_count",
    "actual_snapshot_count",
    "unready_accounting_month_count",
    "unready_accounting_months",
    "currency_missing_value_count",
    "entity_source_hit_count",
    "cost_missing_value_count",
    "ddp_missing_value_count",
    "net_delivery_missing_value_count",
    "ddp_turnover_days",
    "avg_inventory_cost_rmb",
    "avg_inventory_ddp_rmb",
    "net_delivery_rmb",
    "avg_inventory_cost_original",
    "avg_inventory_ddp_original",
    "net_delivery_original",
    "period_natural_days",
    "snapshot_month_count",
    "receipt_coverage",
    "net_delivery_amount_rmb",
    "net_receipt_amount_rmb",
    "settlement_band",
    "sample_bill_count",
    "average_net_debt_rmb",
    "delivery_amount_rmb",
    "average_net_debt_original",
    "delivery_amount_original",
    "effective_month_count",
    "excluded_negative_bill_count",
    "excluded_open_balance_bill_count",
}
PUBLIC_FACT_FIELDS.update(analytical_handlers.public_fact_fields())
PUBLIC_FACT_FIELDS.update(_FABRIC_FACT_FIELDS)
PUBLIC_FACT_FIELDS.update({'high_net_rolls','high_known_net_rolls','high_gross_rolls','high_known_gross_rolls',
    'high_missing_price_rows','high_missing_roll_rows','high_price_anomaly_rows','unit_high_net_rolls',
    'unit_high_known_net_rolls','unit_high_known_gross_rolls','unit_high_missing_price_rows',
    'unit_high_missing_roll_rows','unit_high_price_anomaly_rows'})

PUBLIC_FACT_FIELDS.update({'opening_group_count','closing_group_count','opening_uncertain_membership_rows',
    'monthly_opening_snapshot_rows','monthly_closing_available','monthly_whitelist_rows',
    'monthly_whitelist_unknown_rows','monthly_opening_uncertain_groups'})

PUBLIC_FACT_FIELDS.update({'scope_net_rolls', 'scope_high_known_net_rolls', 'unit_high_known_net_rolls', 'scope_known_net_rolls', 'sales_high_missing_roll_rows', 'scope_high_net_rolls', 'sales_high_missing_price_rows', 'sales_high_known_net_rolls', 'unit_net_rolls', 'unit_high_net_rolls', 'population_sales_groups', 'sales_high_net_rolls', 'sales_net_rolls', 'unit_known_net_rolls', 'sales_known_net_rolls'})

PUBLIC_FACT_FIELDS.update({'scope_high_missing_price_rows','scope_high_missing_roll_rows','scope_missing_roll_rows','sales_missing_roll_rows'})

PUBLIC_FACT_FIELDS.update({'high_net_quantity','high_known_net_quantity','high_gross_quantity','high_known_gross_quantity','high_missing_quantity_rows','unit_high_net_quantity','unit_high_known_net_quantity','unit_high_known_gross_quantity','unit_high_missing_quantity_rows'})

# Published read-only: this is a shared review boundary, not per-call state.
PUBLIC_FACT_FIELDS = frozenset(PUBLIC_FACT_FIELDS)
